### ISSUE TITLE
macOS Sonoma

### ISSUE THREAD

**Issue by iT0G** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#10]
Hello guys. Have you tried Sonoma yet on this configuration, will it be still possible to operate on it?

**Comment by wintermist** [comment]
It is very much possible to use Sonoma on this machine but with compromises, of course. Until and unless the OCLP team comes up with some other way (that does not involve volume patching) to patch Broadcom's wifi, I think everyone should stick to Ventura. IDK the scenario with Intel cards though.
