### ISSUE TITLE
Continuity Features

### ISSUE THREAD

**Issue by iT0G** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#2]
Hey again. I just noticed that some of the continuity features don't work. 

Features that do work:
AirDrop
Universal Clipboard
Text Message Forwarding
iPhone Cellular Calls
Instant Hotspot
Handoff

Features that don't work:
AirPlay to Mac
Continuity Markup
Continuity Sketch
Sidecar
Universal Control

Not tested features:
Apple Pay
Auto Unlock

Is there anything that you can do to make this features work? Like I think that you can try using FeatureUnlock kext to make some of them work. 

Plus I think that you should enable ExtendBTFeatureFlags under Quirks so people can use your config out the box with out further editing after right SMBIOS edit. ;)

**Comment by wintermist** [comment]
What WLAN/BT card are you using?

**Comment by iT0G** [comment]
Currently I am using BCM94350, I used a native Lenovo part from Yoga
710-14ISK.

**Comment by wintermist** [comment]
> Currently I am using BCM94350 for both BT and wlan, I used a native Lenovo part from Yoga 710-14ISK.

BCM94350 is also supported. Strange that universal control is not working. My understanding is that, unless you use an actual Apple branded Broadcom card meant for an actual Apple computer, some features will never work. See [this](https://github.com/acidanthera/bugtracker/issues/1571). I have seen similar arguments for some other features as well.

> Features that don't work: AirPlay to Mac Continuity Markup Continuity Sketch Sidecar Universal Control
> 
> Not tested features: Apple Pay Auto Unlock

Unfortunately, I don't have any other Apple device with me at the moment to test whether above features work in my system or not. 

> Plus I think that you should enable ExtendBTFeatureFlags under Quirks so people can use your config out the box with out further editing after right SMBIOS edit. ;)

Thanks. Will look into it. :)

**Comment by iT0G** [comment]
> > Currently I am using BCM94350 for both BT and wlan, I used a native Lenovo part from Yoga 710-14ISK.
> 
> test
> 
> BCM94350 is also supported. Strange that universal control is not working. My understanding is that, unless you use an actual Apple branded Broadcom card meant for an actual Apple computer, some features will never work. See [this](https://github.com/acidanthera/bugtracker/issues/1571). I have seen similar arguments for some other features as well.
> 
> 
> 
> > Features that don't work: AirPlay to Mac Continuity Markup Continuity Sketch Sidecar Universal Control
> 
> > 
> 
> > Not tested features: Apple Pay Auto Unlock
> 
> 
> 
> Unfortunately, I don't have any other Apple device with me at the moment to test whether above features work in my system or not. 
> 
> 
> 
> > Is there anything that you can do to make this features work? Like I think that you can try using FeatureUnlock kext to make some of them work.
> 
> 
> 
> FeatureUnlock.kext is meant for those SMBIOS for which Apple has decided not to provide a certain or a set of features. IIRC, It merely makes those features available to those machines, it does not actually do anything to fix any underlying problem.
> 
> 
> 
> > Plus I think that you should enable ExtendBTFeatureFlags under Quirks so people can use your config out the box with out further editing after right SMBIOS edit. ;)
> 
> 
> 
> Thanks. Will look into it. :)

**Comment by iT0G** [comment]
>Universal control does work for me, but then again, I use a WLAN/BT combo card that uses a Broadcom chipset which is (almost) natively supported by the macOS.
>
>Hmm, it is really strange that universal control do work for you but do not work for me. What wlan/bt card are you using at the moment? 
>
> BCM94350 is also supported. Strange that universal control is not working. My understanding is that, unless you use an actual Apple branded Broadcom card meant for an actual Apple computer, some features will never work. See [this](https://github.com/acidanthera/bugtracker/issues/1571). I have seen similar arguments for some other features as well.
>
>I think you're right about Apple branded card. But I don't think that it is completely true what is shown in the link, I am using same card as shown in the link but I am able to use personal hotspot.
>
> Unfortunately, I don't have any other Apple device with me at the moment to test whether above features work in my system or not. 
> 
> If you will have any chance to test it somehow in near future please share your results.
> 
> FeatureUnlock.kext is meant for those SMBIOS for which Apple has decided not to provide a certain or a set of features. IIRC, It merely makes those features available to those machines, it does not actually do anything to fix any underlying problem.
> 
> Oh, wow, I didn't know that, okay. 😄

**Comment by wintermist** [comment]
> Hmm, it is really strange that universal control do work for you but do not work for me. What wlan/bt card are you using at the moment?

I am using a Lenovo branded BCM94352Z (aka DW1560 in case of Dell branded ones). The details of this card are already on the README.

> I think you're right about Apple branded card. But I don't think that it is completely true what is shown in the link, I am using same card as shown in the link but I am able to use personal hotspot.

That is good to hear. That issue is quite old, so some things might have changed in the meantime.
> If you will have any chance to test it somehow in near future please share your results.
> 
Sure. Will do.
