### ISSUE TITLE
Can't wake from sleep or lockscreen

### ISSUE THREAD

**Issue by bootlegseahorse** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#4]
Workaround: add -wegnoegpu in boot argument

**Comment by wintermist** [comment]
`-wegnoegpu` is not needed unless you have a discrete graphics chip that is unsupported by macOS. Not sure how it relates to sleep problems. Anyways, sleep works perfectly fine in my case, but my Yoga-710 variant does not come with a discrete graphics chip.

**Comment by bootlegseahorse** [comment]
Thanks man. 

My version of the Yoga-710 has an nVIDIA 940MX GPU, that's probably why it needs the -wegnoegpu argument. Anyways a better workaround is probably patching the DSDT which I'm too lazy to do.
