### ISSUE TITLE
Adding YogaSMC might be a good idea.

### ISSUE THREAD

**Issue by iT0G** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#5]
Hey, how you doing?!

I recently learned about [YogaSMC](https://github.com/zhen-zen/YogaSMC). You might want to check and add it out. 

Second thing is that I tried out [FeatureUnlock](https://github.com/acidanthera/FeatureUnlock). It has resolved my "AirPlay to Mac not working" problem. So you might want to add it.

Plus, I think it would be nice to add a note for people with NVIDIA 940MX, that they have to add `-wegnoegpu` as a boot argument (`Root > NVRAM > Add > 7C436110-AB2A-4BBB-A880-FE41995C9F82 > boot-args > `) as there are a lot of people that are new to Hackintosh and might not know how and what to do as without that argument brightness and sleep won't work at all.

**Comment by wintermist** [comment]
> I recently learned about [YogaSMC](https://github.com/zhen-zen/YogaSMC).

YogaSMC is not going to be added for the time being.

> Second thing is that I tried out [FeatureUnlock](https://github.com/acidanthera/FeatureUnlock). It has resolved my "AirPlay to Mac not working" problem. So you might want to add it.

Thanks for testing and letting me know. I have added the kext.

> Plus, I think it would be nice to add a note for people with NVIDIA 940MX, that they have to add `-wegnoegpu`.....

Added. Thanks again. :)
