### ISSUE TITLE
FileVault incorrect password

### ISSUE THREAD

**Issue by jordanwarnes** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#6]
Has anyone tried enabling FileVault?

I have a similar laptop (710-14ISK) and have tried your EFI as well as creating my own, but whenever I enable FileVault and reboot it says the password is incorrect even when it's not.

Has anyone else ran into this issue or knows how to fix it?

**Comment by wintermist** [comment]
Hi, I don't use FireVault, so I can't comment on it. But I can see that your laptop has a SkyLake CPU. You might want to change your SMBIOS to MacBookPro13,1. 

Also, have you tried following the Dortania **_[guide](https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html)_** on FireVault?

**Comment by jordanwarnes** [comment]
I have followed the Dortania guide closely and enabled all the options that were specified [here](https://dortania.github.io/OpenCore-Post-Install/universal/security/filevault.html).

Unfortunately I can't use the MacBookPro13,1 SMBIOS as it was [dropped](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/skylake.html#platforminfo) in macOS Ventura. However they are very similar and Skylake can be [spoofed](https://dortania.github.io/OpenCore-Install-Guide/extras/ventura.html#supported-hardware) as Kabylake.

I've read through all of the Dortania guides but haven't found anything relating to this issue, I have had the same issue on previous versions of macOS too.

**Comment by jordanwarnes** [comment]
Closing this for now perhaps someone can comment on how they fixed this issue in the future.
