### ISSUE TITLE
OC: grabbed zero system-id for SB, this is not allowed. Halting on critical error.

### ISSUE THREAD

**Issue by kevin-Curry** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#7]
OC: grabbed zero system-id for SB, this is not allowed. Halting on critical error.
Haltino on critical error

**Comment by kevin-Curry** [comment]
Secure Boot is disabled

**Comment by jordanwarnes** [comment]
Have you tried this in your config.plist?

`Misc -> Security -> SecureBootModel`

to `Disabled`

Make sure you are following the Dortania guide this error was mentioned in the troubleshooting section: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#oc-failed-to-find-sb-model-disable-halting-on-critical-error

**Comment by wintermist** [comment]
Set "SecureBootModel" to "Disabled" in your config.plist.
