### ISSUE TITLE
Wi-Fi and Touch Screen not working

### ISSUE THREAD

**Issue by kevin-Curry** [wintermist/Lenovo-Yoga-710-14IKB-Hackintosh#8]
Wi-Fi and Touch Screen not working

**Comment by bootlegseahorse** [comment]
Touchscreen only works after waking from sleep. Try again. 

Use a supported Wi-Fi card from Broadcom or Intel (AirPortItlwm.kext and IntelBluetoothInjector.kext are needed for Intel cards).
